name: aerospike-server.docker

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools-alt:arm-ubuntu-20.04

build:
  - name: default
    environment:
      BUILD_TRIGGER: 2

qe-registry:
  - dockerfile: enterprise/ubuntu24.04/master.Dockerfile
    tag: docker.qe.aerospike.com/aerospike/aerospike-server-enterprise:arm-master
  - dockerfile: enterprise/ubuntu24.04/preview.Dockerfile
    tag: docker.qe.aerospike.com/aerospike/aerospike-server-enterprise:arm-preview
allow-rebuild: True
