name: aerospike-server.docker

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-20.04

build:
  - name: default
    environment:
      BUILD_TRIGGER: 6

qe-registry:
  - dockerfile: buildtest/bad.Dockerfile
    tag: docker.qe.aerospike.com/aerospike/test:x86-bad
  #- dockerfile: community/ubuntu24.04/nightly.Dockerfile
  #  tag: docker.qe.aerospike.com/aerospike/aerospike-server:x86-preview
allow-rebuild: True
