name: aerospike-server.docker

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-20.04

build:
  - name: default
    environment:
      BUILD_TRIGGER: 2

qe-registry:
  - dockerfile: enterprise/ubuntu24.04/nightly.Dockerfile
    tag: docker.qe.aerospike.com/aerospike/aerospike-server-enterprise:x86-master
  - dockerfile: community/ubuntu24.04/nightly.Dockerfile
    tag: docker.qe.aerospike.com/aerospike/aerospike-server:x86-master
allow-rebuild: True
