variable "VERSION_SUFFIX" {
    default = "1"
}

variable "REVISION" {
    default = ""
}

variable "CREATED" {
    default = ""
}

variable "INCLUDE_LATEST" {
    default = false
}

variable "VERSION" {
    default = "latest"
}



# This file contains the targets for the test images.
# This file is auto-generated by the update.sh script and will be wiped out by the update.sh script.
# Please don't edit this file.
#
# Build all test/push images:
#      docker buildx bake -f bake.hcl [test | push] --progressive plain [--load | --push]
# Build selected images:
#      docker buildx bake -f bake.hcl [target name, ...] --progressive plain [--load | --push]

#------------------------------------ test -----------------------------------

group "test" {
    targets=["enterprise_ubuntu24-04_amd64", "enterprise_ubuntu24-04_arm64", "federal_ubuntu24-04_amd64", "community_ubuntu24-04_amd64", "community_ubuntu24-04_arm64"]
}

target "enterprise_ubuntu24-04" {
    tags = []
    platforms=["linux/amd64,linux/arm64"]
    context="./enterprise/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "enterprise"
    }
    labels={}
}

target "enterprise_ubuntu24-04_arm64" {
    tags = []
    platforms=["linux/arm64"]
    context="./enterprise/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "enterprise"
    }
    labels={}
}

target "federal_ubuntu24-04" {
    tags = []
    platforms=["linux/amd64"]
    context="./federal/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "federal"
    }
    labels={}
}

target "community_ubuntu24-04" {
    tags = []
    platforms=["linux/amd64,linux/arm64"]
    context="./community/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "community"
    }
    labels={}
}

target "community_ubuntu24-04_arm64" {
    tags = []
    platforms=["linux/arm64"]
    context="./community/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "community"
    }
    labels={}
}

#------------------------------------ push -----------------------------------

group "push" {
    targets=["enterprise_ubuntu24-04", "federal_ubuntu24-04", "community_ubuntu24-04"]
}

target "enterprise_ubuntu24-04" {
    tags = []
    platforms=["linux/amd64,linux/arm64"]
    context="./enterprise/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "enterprise"
    }
    labels={}
}

target "federal_ubuntu24-04" {
    tags = []
    platforms=["linux/amd64"]
    context="./federal/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "federal"
    }
    labels={}
}

target "community_ubuntu24-04" {
    tags = []
    platforms=["linux/amd64,linux/arm64"]
    context="./community/ubuntu24.04"
    args={
        "AEROSPIKE_EDITION" = "community"
    }
    labels={}
}

