# This file contains the targets for the test images.
# This file is auto-generated by the update.sh script and will be wiped out by the update.sh script.
# Please don't edit this file.
#
# Build all test/push images:
#      docker buildx bake -f images/6.0/bake.hcl [test | push] --progressive plain [--load | --push]
# Build selected images:
#      docker buildx bake -f images/6.0/bake.hcl [target name, ...] --progressive plain [--load | --push]

#------------------------------------ test -----------------------------------

group "test" {
    targets=["enterprise_debian10_amd64", "federal_debian10_amd64", "community_debian10_amd64"]
}

target "enterprise_debian10_amd64" {
    tags=["aerospike/aerospike-server-enterprise-amd64:6.0.0.22", "aerospike/aerospike-server-enterprise-amd64:latest"]
    platforms=["linux/amd64"]
    context="./images/6.0/enterprise/debian10"
}

target "federal_debian10_amd64" {
    tags=["aerospike/aerospike-server-federal-amd64:6.0.0.22", "aerospike/aerospike-server-federal-amd64:latest"]
    platforms=["linux/amd64"]
    context="./images/6.0/federal/debian10"
}

target "community_debian10_amd64" {
    tags=["aerospike/aerospike-server-community-amd64:6.0.0.22", "aerospike/aerospike-server-community-amd64:latest"]
    platforms=["linux/amd64"]
    context="./images/6.0/community/debian10"
}

#------------------------------------ push -----------------------------------

group "push" {
    targets=["enterprise_debian10", "federal_debian10", "community_debian10"]
}

target "enterprise_debian10" {
    tags=["aerospike/aerospike-server-enterprise:6.0.0.22", "aerospike/aerospike-server-enterprise:6.0.0.22_1"]
    platforms=["linux/amd64"]
    context="./images/6.0/enterprise/debian10"
}

target "federal_debian10" {
    tags=["aerospike/aerospike-server-federal:6.0.0.22", "aerospike/aerospike-server-federal:6.0.0.22_1"]
    platforms=["linux/amd64"]
    context="./images/6.0/federal/debian10"
}

target "community_debian10" {
    tags=["aerospike/aerospike-server:6.0.0.22", "aerospike/aerospike-server:6.0.0.22_1"]
    platforms=["linux/amd64"]
    context="./images/6.0/community/debian10"
}

