# This file contains the targets for the test images.
# This file is auto-generated by the update.sh script and will be wiped out by the update.sh script.
# Please don't edit this file.
#
# Build all test/push images:
#      docker buildx bake -f images/6.0/bake.hcl [test | push] --progressive plain [--load | --push]
# Build selected images:
#      docker buildx bake -f images/6.0/bake.hcl [target name, ...] --progressive plain [--load | --push]

#------------------------------------ test -----------------------------------

group "test" {
    targets=["enterprise_debian11_amd64", "federal_debian11_amd64", "community_debian11_amd64"]
}

target "enterprise_debian11_amd64" {
    tags=["aerospike/aerospike-server-enterprise-amd64:6.0.0.22", "aerospike/aerospike-server-enterprise-amd64:6.0"]
    platforms=["linux/amd64"]
    context="./images/6.0/enterprise/debian11"
}

target "federal_debian11_amd64" {
    tags=["aerospike/aerospike-server-federal-amd64:6.0.0.22", "aerospike/aerospike-server-federal-amd64:6.0"]
    platforms=["linux/amd64"]
    context="./images/6.0/federal/debian11"
}

target "community_debian11_amd64" {
    tags=["aerospike/aerospike-server-community-amd64:6.0.0.22", "aerospike/aerospike-server-community-amd64:6.0"]
    platforms=["linux/amd64"]
    context="./images/6.0/community/debian11"
}

#------------------------------------ push -----------------------------------

group "push" {
    targets=["enterprise_debian11", "federal_debian11", "community_debian11"]
}

target "enterprise_debian11" {
    tags=["aerospike/aerospike-server-enterprise:6.0.0.22", "aerospike/aerospike-server-enterprise:6.0.0.22_1", "aerospike/aerospike-server-enterprise:6.0"]
    platforms=["linux/amd64"]
    context="./images/6.0/enterprise/debian11"
}

target "federal_debian11" {
    tags=["aerospike/aerospike-server-federal:6.0.0.22", "aerospike/aerospike-server-federal:6.0.0.22_1", "aerospike/aerospike-server-federal:6.0"]
    platforms=["linux/amd64"]
    context="./images/6.0/federal/debian11"
}

target "community_debian11" {
    tags=["aerospike/aerospike-server:6.0.0.22", "aerospike/aerospike-server:6.0.0.22_1", "aerospike/aerospike-server:6.0"]
    platforms=["linux/amd64"]
    context="./images/6.0/community/debian11"
}

