# generated 2025-05-28 21:04:37
feature-key-version              2
serial-number                    659194956

account-name                     Aerospike
account-ID                       Aerospike_Eval

valid-until-version              8.9

asdb-change-notification         true
asdb-cluster-nodes-limit         1
asdb-compression                 true
asdb-encryption-at-rest          true
asdb-flash-index                 true
asdb-ldap                        true
asdb-pmem                        true
asdb-rack-aware                  true
asdb-secrets                     true
asdb-strong-consistency          true
asdb-vault                       true
asdb-xdr                         true
database-recovery                true
elasticsearch-connector          true
graph-service                    true
mesg-jms-connector               true
mesg-kafka-connector             true
presto-connector                 true
pulsar-connector                 true
spark-connector                  true

----- SIGNATURE ------------------------------------------------
MEUCIAsCppOFndv34l1eOSJdNfG4kTHqgKFVvjPugQbDT5jYAiEA/eXUiIvHb9f/
FH7xaKVHQHZiLZMj1nJnIBaLKEpF3qok
----- END OF SIGNATURE -----------------------------------------
