name: Docker Build
permissions:
  contents: read
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  generate-check:
    name: Generate (no diff)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Generate Dockerfiles for 8.1
        run: ./docker-build.sh -g 8.1
      - name: Should not change anything
        run: '[ -z "$(git diff --stat)" ] || (git diff --stat; exit 1)'

  build-and-test:
    name: Build and test 8.1
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Build
        run: ./docker-build.sh -t 8.1
      - name: Test
        run: ./test.sh 8.1
